apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-web
spec:
  selector:
    matchLabels:
      app: app-web
  replicas: 3
  template:
    metadata:
      labels:
        app: app-web
    spec:
      containers:
      - name : app-web
        image: nginx
