apiVersion: v1
kind: Pod
metadata:
  name: pod-files
  labels:
    name: pod-files
spec:
  containers:
  - name: pod-files
    image: nginx
    #Monta o volume criada no fim do arquivo
    volumeMounts:
      - mountPath: /mnt/azure
        name: azure
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
# abaixo cria o volume 
  volumes:
    - name: azure
      csi:
        driver: file.csi.azure.com
        readOnly: false
        volumeAttributes:
          secretName: azure-secret
          shareName: aksfiles
