apiVersion: v1
kind: Pod
metadata:
  name: empty-dir
  labels:
    name: empty-dir
spec:
  containers:
  - name: empty-dir-a
    image: busybox
    command: ['tail', '-f', '/dev/null']
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: /cache
        name: cache
  - name: empty-dir-b
    image: busybox
    command: ['tail', '-f', '/dev/null']
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: /cache
        name: cache
  volumes:
    - name: cache
      emptyDir: {}