apiVersion: v1
kind: Pod
metadata:
  name: pod-container
spec:
  containers:
  - name: pod-container01
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  - name: pod-container02
    image: alpine
    command: ["watch", "wget","-q0","localhost"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    
