apiVersion: v1
kind: Pod
metadata:
  name: pod01
spec:
  containers:
  - name: container01
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
